### ISSUE TITLE
汉化的是哪部分

### ISSUE THREAD

**Issue by Stongtong** [liuwenru/Apache-Ambari-ZH#6]
想问一下,汉化的是哪部分,为什么在下载的源码中都没有体现汉化?

**Comment by Stongtong** [comment]
可以加一个readme详细说说吗,避免误导大家

**Comment by liuwenru** [comment]
message.js 因为ambari的前端是一个纯前端的工程，所以如果你要是想使用的话需要重新编译这个包去使用，在ambari-web上`brunch build`即可，然后把生成public文件夹覆盖到ambari-server的`/usr/lib/ambari-server/web`目录即可。

**Comment by liuwenru** [comment]
我build了一个放上去了已经
